name: Deploy Javadoc to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  javadoc:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 21
          target-folder: docs
          project: maven
          javadoc-source-folder: target/reports/apidocs
